websocket: avoid WebSocketClosedError double/nested exception
Tracking the exception that was being handled when another exception
was raised is a new feature in Python-3, causing this:

    Traceback (most recent call last):
      File "/...-packages/tornado/websocket.py", line 1104, in wrapper
        await fut
    tornado.iostream.StreamClosedError: Stream is closed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/...-packages/tornado/websocket.py", line 1106, in wrapper
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError

This can be selectively avoided using the new Python-3 syntax:

    raise WebSocketClosedException from None